name: personal_finances
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  flutter_card_swiper: 7.0.0
  bloc: 8.1.4
  flutter_bloc: 8.1.5
  equatable: 2.0.5
  get_it: 7.6.7
  firebase_core: 2.27.2
  cloud_firestore: 4.15.10
  go_router: 13.2.1
  path_provider: 2.1.2
  hydrated_bloc: 9.1.5
  fl_chart: 0.66.2
  image_picker: 1.0.7
  iconsax: 0.0.8
  firebase_storage: 11.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background/
    - assets/icons/
